MagaluCloud/s3-specs

.github/workflows/run_tests.yml, bin/configure_profiles.py, docs/configure_profiles.py
Foi criado um workflow para execução manual de algum testes do pytest.
=> Action workflows

.github/workflows/manual-test.yml, .github/workflows/pull-request-test.yml, .github/workflows/run-tests.yml, docs/locking_cli_test.py, docs/locking_test.py, docs/policies_test.py, docs/profiles_policies_test.py, params.example.yaml, pyproject.toml
This branch implements a workflow to run all the tests in the repository when a pull request is opened or reopened.
=> Workflow to run all tests when opening a pull request

.github/workflows/pull-request-test.yml, .github/workflows/run-tests.yml, docs/acl_test.py, docs/cold_storage_test.py, docs/list-buckets_test.py, docs/presigned-urls_test.py, docs/s3_helpers.py, docs/unique-bucket-name_test.py, pyproject.toml
This will make them cleanable by the scheduled cleanup of s3-tester
=> add test- in the beginnig of the bucket names

.github/workflows/pull-request-test.yml, .github/workflows/run-tests.yml, docs/cold_storage_test.py, docs/conftest.py, docs/list-buckets_test.py, docs/locking_cli_test.py, docs/versioning_cli_test.py, docs/versioning_test.py, params.example.yaml, pyproject.toml
Foram recriados os testes 49 e 50 do s3-tester.
Dois testes foram criados, um utilizando boto 3, e o outro utilizando mgc, rclone e aws cli.
=> Versioning test

.github/pull_request_template.md
Add a Pull Request template to standardize and improve the quality of PR descriptions in the repository.
=> add PR Template

bin/exporter.py, docs/benchmark_test.py, docs/conftest.py, docs/consistency_test.py, pyproject.toml, report/benchmark_results.csv, report/report-inconsistencies.csv
Realizar teste de incosistencias e exportar os dados para o grafana.
Validar quanto tempo leva ate garantir a consistencia em algumas ações.
Conseguir ter um historico de melhoria/piora de inconsistencias.
[STK-ABC6](https://kanban-force.web.app/boards/63d991aaf03baf6cfdc0f999?cardId=67c20c1725028f1f745eabc6)
=> feat: consistencies test and exporter

docs/benchmark_test.py, pyproject.toml
Adicionar marker ao teste de benchmark para isola-lo
Adicionar marker ao teste de benchmark para isola-lo
Permitir executar somente o teste de benchmark
=> add marker on benchmark test

.gitignore, reports/.gitignore, reports/src/__main__.py, reports/src/git_local_extractor.py, reports/src/logDataclasses.py
O pr tem como objetivo o scrapper do git actions e geracao de files do prometheus
Added: Nova feature de scrapping do git
Fixed: Bug de tipos que estava ocorrendo
Permitindo a criação de tabelas no grafana
[[Link para o card no Kanban](URL_DO_CARD)](https://kanban-force.web.app/boards/63d991aaf03baf6cfdc0f999?cardId=67b87a641ab0d008f7971601)
=> Gh actions scrapper

.gitignore, bin/exporter.py, docs/benchmark_test.py, docs/consistency_test.py, output/benchmark_results.csv, output/report_inconsistencies.csv
Descreva claramente o objetivo deste PR. O que está sendo implementado ou corrigido?
Explique o motivo pelo qual esta mudança é necessária. Isso pode incluir a resolução de um bug, uma melhoria ou uma nova funcionalidade.
O que se espera alcançar com essa mudança? Quais são os resultados ou comportamentos esperados após a implementação?
=> Fix exported tests

reports/run.sh
Descreva claramente o objetivo deste PR. O que está sendo implementado ou corrigido?
Explique o motivo pelo qual esta mudança é necessária. Isso pode incluir a resolução de um bug, uma melhoria ou uma nova funcionalidade.
O que se espera alcançar com essa mudança? Quais são os resultados ou comportamentos esperados após a implementação?
=> add test categories

.github/pull_request_template.md
Imporve pr template
Old template lacks import info
Improve ux
=> Refactor: change on pull request template allowing more descritive info

bin/purge_test_buckets.py
Aumentar o tempo de limpeza de buckets para evitar conflito com buckets maiores ou testes grandes.
Alterado de 2 para 6 horas.
=> increase clean time to 6 hours

.github/workflows/manual-test.yml
- [ x ] Bug Fix
Corrigindo erro no action de test manual 
Corrigindo o erro da falta de input name no workflow do teste manual
=> fix manual-test.yml input required

bin/exporter.py, reports/src/git_local_extractor.py
Com objetivo de melhorar dados de input do grafana e prometheus
Adicionado Counter que contara a quantidade de erros em cada workflow, em adicao, colocado um checker para garantir que o workflow nao seja reprocessado
[[Link para o card no Kanban](URL_DO_CARD)](https://kanban-force.web.app/boards/67b35352a198404105930ec0?cardId=67e15646bf4f92bdb29100f2)
=> Processed workflow tracker

justfile, src/s3_specs/docs/bucket_basic_test.py, src/s3_specs/docs/conftest.py, src/s3_specs/docs/utils/crud.py
Falta testes basicos de crud de buckets e objects com boto3 para o Sauron, este patch inclui alguns básicos de bucket.
[Link para o card no Kanban](https://kanban-force.web.app/boards/67b35352a198404105930ec0?cardId=67e15646923bd49f1507c652)
=> new boto3 tests for basic bucket operations

bin/exporter.py, reports/src/git_local_extractor.py
- [x ] Refactor
- [x ] Bug Fix
Evitar geracao de numeros gigantes pelo exporter
limpeza dos paruqets para que eles contenham apenas os dados da ultima query do git_local_extractor 
[[Link para o card no Kanban](URL_DO_CARD)](https://kanban-force.web.app/boards/67b35352a198404105930ec0?cardId=67e15646bf4f92bdb29100f2)
=> Exporter big numbers fix

reports/src/logDataclasses.py
Erro em elitura e salvamento de parquets
Adicao de tratamento de erros nas devidaas funcoes
[[Link para o card no Kanban](URL_DO_CARD)](https://kanban-force.web.app/boards/67b35352a198404105930ec0?cardId=67e15646bf4f92bdb29100f2)
=> Fix: Added error control to parquet reading and saving

reports/src/logDataclasses.py
Erro ao carregar parquets
Garantir que parquets sejam criados e lidos
=> Fix: removed existence test from load_parquets

src/s3_specs/docs/conftest.py, src/s3_specs/docs/tools/utils.py
Alteração feita para validar as credenciais estava com um bug nos testes de acl
Nesse PR é criado uma nova fixture para obter os perfis e verificar se são mesmo tenant ou não.
=> fix: false positive configure error

src/s3_specs/docs/big_objects_test.py, src/s3_specs/docs/conftest.py
Testes de big objects estão com erros de implementação, skipando enquanto não resolve
=> Set skip in big objects test

.github/workflows/pull-request-extra-test.yml, .github/workflows/pull-request-test.yml
Muitos CIs rodando durante os prs
=> set ready_for_review as type for pull_request trigger

.github/workflows/pull-request-extra-test.yml, .github/workflows/pull-request-test.yml, .github/workflows/recurrent-tests.yml
Descreva claramente a motivação deste PR, esta podendo ser uma necessidade, pedido ou opcional. 
Descreva em detalhes as alterações e obejtivo da mudança de seu PR.
=> remover clean-up dos testes recorrentes

src/s3_specs/docs/versioning_cli_test.py
Resolucao do bug no versioning_cli
Adicionado fixture para rodar no mgc
=> Fix: Versioning cli added active_mgc_workspace fixture

.github/workflows/generate-docker-image-daily.yml, .github/workflows/pull-request-extra-test.yml, .github/workflows/pull-request-test.yml, .github/workflows/recurrent-tests.yml
Devido a quantidade de runners usados
=> Desativando workflows temporariamente

src/s3_specs/docs/consistency_test.py
Diminuir o tempo de run
Acelerar o tempo do run para termos metricas
=> decrease from 100k to 10k objects

src/s3_specs/docs/conftest.py, src/s3_specs/docs/s3_helpers.py
Resolver problema que tem travado os workers 
Foi alterado a forma que as fixtures de versioning deletava os objetos
=> Update versioning fixture teardown process

.github/workflows/recurrent-tests.yml, .github/workflows/run-tests.yml
Teste recorrentes bugados
Workflow não está passando de forma correta os valores dos markers
=> fix workflows - recurrent and run-tests

src/s3_specs/docs/objects_list_cli.py
Validar erros reportados quando é utilizado espaços como prefixo.
Adiciona um cenário amais para o teste onde é passado um prefixo de objeto contendo espaço.
=> add more scenarios with space in the prefix

src/s3_specs/docs/conftest.py, src/s3_specs/docs/objects_list_cli.py
Adicionar novos cenários no teste
Foi adicionado novos cenários no testes incluindo alguns caracteres especiais no prefixo do object
=> including new characteres in testcases

pyproject.toml, src/s3_specs/docs/cold_storage_cli.py, src/s3_specs/docs/cold_storage_test.py, src/s3_specs/docs/conftest.py, src/s3_specs/docs/tools/cold_storage.py, src/s3_specs/docs/tools/utils.py
S3-tester para s3-specs cold storage
Adicionado teste de cold-storage de upload e multipart upload
=> Cold storage cli

.github/workflows/manually-run-tests-with-latests-tools.yml
Criar workflow de homologação
Foi criado um workflow com os testes a serem executados em homologação
=> feat: add workflow to run tests in homologacao

.github/workflows/manually-run-homologacao-tests.yml, .github/workflows/run-tests-with-report.yml, run_tests_and_generate_report.py, src/s3_specs/docs/conftest.py
Adicionar uma maneira fácil de rodar testes de homologação
Foi adicionado um workflow que facilita o processo de execução dos testes para homologação
=> add manually way to run homologacao tests

src/s3_specs/docs/conftest.py
=> fix --dev-run args

.github/workflows/generate-docker-image-on-push.yml, justfile, src/s3_specs/docs/bucket_sharing_cli.py, src/s3_specs/docs/bucket_sharing_test.py, src/s3_specs/docs/conftest.py, src/s3_specs/docs/locking_cli_test.py, src/s3_specs/docs/service_account_test.py, src/s3_specs/docs/versioning_cli_test.py
=> fix dev run

src/s3_specs/docs/cold_storage_cli.py, src/s3_specs/docs/cold_storage_test.py
=> add us-east-1 to run cold storage when using dev flag

params/br-se1.yaml
Tempo de testes de policy muito altos por conta de waiting time
Diminuicao do wait time nos arquivos runers
=> Changes: setting policy values to 0 on se1

.github/workflows/generate-docker-image-on-push.yml, oci/tools_latest.Containerfile
Corrigir bug na criação da imagem latest
Após algumas atualizações do MGC CLI, começou a ocorrer erros durante a instalação do mesmo da forma que estava sendo instalado. Foi atualizado para instalar a ultima versão disponível usando apt install.
=> fix: fixed 404 error during mgccli install in latest image builder

src/s3_specs/docs/delete_all_cli_test.py, src/s3_specs/docs/s3_helpers.py
feat: create teste for delet -all
Adicionar novos testes de delete all
[Link para o card no Kanban](https://kanban-force.web.app/boards/63d991aaf03baf6cfdc0f999?cardId=6834d795f9a4a36f704a51ac)
=> feat: create test for delete all

.github/workflows/generate-docker-image-on-push.yml, src/s3_specs/docs/cold_storage_cli_test.py
Skipar testes cross account de cold storage quando estiver rodando em modo dev
=> chore: add skip_dev in cold storage test cross account

.github/workflows/cleanup-tests.yml, .github/workflows/run-cleanup.yml, bin/purge_test_buckets.py
Melhorar o processo de cleanup do s3specs. 
Buckets lotados, o objetivo desse pr é melhorar a forma que é realizado o cleanup do s3specs, e adicionar um workflow que roda manual e diariamente para a limpeza dos perfis
=> fix: cleanup script

src/s3_specs/docs/consistency_test.py
Removido marker do teste de consistencia para nao rodar no setup de 12h
=> fix: remove marker of consistency test

.github/workflows/run-tests-with-report.yml, .github/workflows/run-tests.yml, bin/webhook.py, run_tests_and_generate_report.py
- [] Feature
Para facilitar o monitoramento das runs no s3-specs, adiciona um webhook que notifica quando os testes falham. 
Adicionado nos yml a action que faz o envio de execuções com erros no canal do gchat
=> feat: add gchat webhook

.github/workflows/recurrent-tests-12h.yml, .github/workflows/recurrent-tests-1h.yml, .github/workflows/recurrent-tests-6h.yml
Descreva claramente a motivação deste PR, esta podendo ser uma necessidade, pedido ou opcional. 
Descreva em detalhes as alterações e obejtivo da mudança de seu PR.
=> feat: change recurrent tests

.github/workflows/generate-docker-image-daily.yml, .github/workflows/recurrent-tests-12h.yml, .github/workflows/recurrent-tests-1h.yml, .github/workflows/recurrent-tests-6h.yml, .github/workflows/recurrent-tests.yml
PR to add a manual trigger to workflows
=> feat: add manual trigger for actions

.github/workflows/daily-tests-with-latest-and-nightly-tools.yml
add manual trigger to github action
=> add manual trigger to github action

.github/workflows/generate-docker-image-dev.yml, .github/workflows/generate-docker-image.yml, .github/workflows/manual-test.yml, oci/tests_dev.Containerfile, oci/tools_dev.Containerfile
Adicionar um workflow permitindo o uso de uma branch mgc para gerar imagem e rodar nos testes manuais.
=> feat: new workflow

.github/workflows/bucket-monitor.yml, bin/bucket_monitor.py
Notei que alguns testes estavam falhando por conta do tenant ter atingido o limite de buckets. 
Um fluxo que roda 2x por dia, 00h e 12h BR, para monitorar quantos buckets existem no nosso tenant de testes, caso esteja >= que 80% do limite, emite uma notificação no canal de testes para executarmos o cleanup.
=> Add Bucket Monitor workflow with twice daily schedule

bin/continuous_consistency_monitor.py, bin/exporter.py, bin/replicator_consistency.py
Alterado testes para usarem ID como identificador do bucket
=> fix: change bucket name to ID and exporter fix

README_S3_Benchmark.md, README_S3_Consistency.md, bin/replicator_consistency.py, src/s3_specs/docs/bucket_basic_test.py
Com o objetivo de diminuir os erros por validação erronea, alterado o teste para validar se todos os buckets retornados contem o prefixo, nao mais fazendo o count deles.
=> Fix test list prefix

justfile, src/s3_specs/docs/rbac_test.py
Skipar testes do rbac quando dev run
=> fix: remove rbac tests from dev run

bin/purge_test_buckets.py
Apagar os buckets com locking ficando pra trás.
Alterado o script de cleanup para fazer deleção normal quando o bucket tiver locking ativado.
=> fix: cleanup
