MagaluCloud/s3-specs

.github/workflows/cleanup-tests.yml, .github/workflows/pull-request-test.yml, bin/purge_test_buckets.py
adiciona um script para remover buckets começados com test- mais velhos que 2 horas e roda como etapa opcional ao fim da pipeline basica de testes
=> Cleanup after ci test

.github/workflows/manual-test.yml, .github/workflows/run-tests.yml
Updating the mgc version today requires changes in two places of a hardcoded string. And we dont have a way to use the manually triggered tests with different versions of the mgc.
This patch turns the version into a variable that can be passed as an argument to the workflow, what can make it easier to write test matrices including different versions of the cli in the future, and make it simple to change the default version to be used when new releases comes.
=> Turn mgc cli version into a variable/input of the run tests workflow

docs/locking_cli_test.py, docs/locking_test.py, params/br-ne1.yaml
On Amazon it is possible to check the retention details of an object using a head_object call. On Magalu Cloud this information is not returned.
This patch replaces head_object with get_object_retention calls on the locking and locking_cli tests.
=> remove head_object from retention tests

.github/workflows/pull-request-extra-test.yml, .github/workflows/pull-request-test.yml, .github/workflows/run-tests.yml, README.md, params/br-ne1.yaml, params/br-se1.yaml
This will allow us to accept PRs in the main branch faster, while still having a lot of test runs in the queue to check and debug new stuff.
=> Split PR CI in two (one essential/fast and one optional/slow/verbose)

.github/workflows/pull-request-extra-test.yml, .github/workflows/run-tests.yml, docs/conftest.py, docs/policies_test.py, docs/profiles_policies_test.py, docs/s3_helpers.py, params.example.yaml, params/br-ne1.yaml, params/br-se1.yaml
Em preparação para as novas actions, relativas a BucketLocking que poderão ser utilizadas em policies. Ajustes nos testes existentes foram necessários.
Aproveitei também para aproximar os testes de policy, que anteriormente não funcionavam como documentação executável (nao continha paragrafos em Markdown) para, na medida do possível serem notebooks minimamente coerentes, então este patch contém alguns refactors além do suporte a actions de locking nas policies.
=> More policy tests

.github/workflows/pull-request-extra-test.yml, .gitignore, docs/conftest.py, docs/locking_cli_test.py, docs/locking_test.py, docs/utils/locking.py, docs/utils/utils.py, params/br-ne1.yaml, params/br-se1.yaml
Três casos de locking, antes não cobertos por testes, com este patch passam a ser: 
- na CLI, unset de default lock config para buckets
- no boto, criação de bucket ja com locking e criação de object já com retention
- allow/deny de actions de locking via bucket policy
Adicionalmente, a introdução de mais waiters e configs de tempos de waiters para que os testes em SE1 principalmente fiquem mais tolerantes (e demorem mais) `a triste realidade da demora no atingimento de consistência eventual.
=> More locking tests

docs/conftest.py, docs/presigned-urls_test.py
Este PR adiciona casos de teste com "subfolders" nos testes de URL pré-assinada
Durante minhas férias um ticket de cliente apontou para um bug com paths contendo subpaths onde a presigned url não estava funcionando.
Espera-se que o caso antes não coberto de presigned urls para objetos cuja object key contenha o caractere barra agora esteja coberto, e por consequência uma regressão deste bug, caso volte, seja detectada.
[STK E610](https://kanban-force.web.app/boards/63d991aaf03baf6cfdc0f999?cardId=67bf26047fd136d6f729e610)
> This patch includes testcases of object keys containing slashes like if the file were in a subfolder path. There was a know issue > related with slashes in the presigned urls that is already fixed so this test is here to prevent any regression.
> 
> This patch modifies …
=> feat: add testcases to prosigned url tests

docs/conftest.py, docs/object_download_cli.py, docs/objects_list_cli.py
> This patch adds a simple spec for the download object command of the MGC CLI.
> 
> The test cases includes object key names with special characteres, slashes (subpath) and spaces.
Este patch adiciona dois testes, um do comando `object-storage objects download` da CLI e um do comando `object-storage objects list`. Entre os casos de teste estão objetos com nomes contendo espaços, barras e caracteres especiais.
Um cliente (a Kognita?) utilizando a mgc cli não consegui fazer ~download (get object) de objetos~ listagem de objetos (list objects) com espaço utilizando a MGC CLI.  
O objetivo deste PR é ter um teste que reproduz o problema em versoes antigas da cli, exemplo 0.34.0 e que este teste passe quando rodado em versoes mais recentes, evitando assim regressões no futuro.
[STK …
=> feat: new test, download object using mgc cli

justfile, pyproject.toml, utils.just
New justfile recipe to lists the available markers
Adiciona um atalho "just catefories" para listar os nomes das categorias disponíveis.
Alguem que queira usar o comando report precisa saber quais as categorias disponiveis, este atalho lista sem que a pessoa precise abrir o pyproject.toml e ir lá fuçar
Uma experiencia mais simples para o dev contributor. Pode ser útil como input para outros comandos no futuro (um menu com fzf por exemplo)
[STK-ED14](https://kanban-force.web.app/boards/63d991aaf03baf6cfdc0f999?cardId=67cef442c1f41ce0d73eed14)
=> new shortcut: just categories

README.md, justfile
This patch adds a new justfile recipe for launching the specs server, for people to read and execute the
specs in a web browser.
Facilitar a vida de quem quiser ler a documentação de uma spec, bem como executá-la pelo navegador.
Como parte do port dos testes legados do s3-tester para a casa nova, ter um atalho simples para subir o ambiente que renderiza os markdowns e que roda as specs via browser será útil como fluxo de trabalho, já que muitos testes antigos eram encarados apenas como código e não documentação. Neste processo de port já pretendo melhorar este lado dos testes serem especificações mesmo.
Espera-se que com um atalho listado nos comandos do just, outros contributors se interessem em ver localmente em suas máquinas como uma spec seria renderizada se/quando convertida para uma …
=> new task: browse

.github/workflows/full-docker-image.yml, justfile, menu.just, oci/full.Containerfile
The version on ubuntu apt packages dont have support for modules this patch makes the installation of the just task manager on our OCI Image configurable to use an specific version.
Arrumar erros causados na utilização das imagens de docker depois que o justfile com modulo de menu entrou..
Nossa imagem de docker utilizava uma versao mais antiga do just, sem suporte a modulos e isto quebrava a experiencia de rodar os testes via conteiner.
Arrumar o uso do projeto via oci image.
Sem card
=> (oci, full) Install just task runner from installation script

bin/exporter.py, docs/benchmark_test.py, docs/consistency_test.py, output/benchmark_results.csv, output/report_inconsistencies.csv
FIX: Resolver um problema que surgia ao executar a criacao de dataclasses entity_time e failures
FIX: Implementar mudanca nos dataframes gerados para tornar as dataclasses armazenadas compativel com o webscrapping presente no file exporter.py
Corrigir o bug descrito e permitir a integração com o api utilizada
[[Link para o card no Kanban](URL_DO_CARD)](https://kanban-force.web.app/boards/63d991aaf03baf6cfdc0f999)
=> FIX: Dataclasses fixing

docs/index.md, docs/runs/policies_test_br-ne1.md, docs/runs/profiles_policies_test_br-ne1.md
policies pages that will be linked in the new policies_cli spec soon.
Publicar 2 novas paginas de "runs" no github pages.
Uma pagina de documentação nova sobre policies via mgc cli vai linkar as specs existentes de boto3 na seção de Docs Relacionadas.
Como hoje a geração e publicação de novas specs no site do github pages ainda é bem manual, o processo é rodar na máquina e commitar os novos .md da pasta run. Este PR é basicamente isto: dois testes que passaram em br-ne1 e viraram páginas de doc.
Ter o resultado das execuções de bucket policy com boto3 na regiáo ne1 publicos na internet.
[STK-ED14](https://kanban-force.web.app/boards/63d991aaf03baf6cfdc0f999?cardId=67cef442c1f41ce0d73eed14)
=> new rendered specs

src/s3_specs/docs/cold_storage_test.py
- [ X ] Refactor
Com a integração dos testes ao Sauron, se viu a necessidade de melhorar um pouco a descrição dos testes de cold storage.
Foi realizado a remoção do prefixo _boto_ no nome dos testes pois não é necessário, e a mudança no nome de uma das funções para inclusão do "cold_storage" e facilitar na filtragem dentro do Sauron.
=> change names of the functions of cold storage tests

bin/exporter.py, reports/src/git_local_extractor.py
Monitorar quais workflows ja foram processados para evitar dados redundantes.
Fix  nos valores do counter, pois, 
Mudanca de counter do s3_specs counter para aumentar em 1 unidade ao inves de n a cada run.
Adicionada funcao que salva os id dos workflows ja processados
[[Link para o card no Kanban](URL_DO_CARD)](https://kanban-force.web.app/boards/67b35352a198404105930ec0?cardId=67e15646bf4f92bdb29100f2)
=> Processed workflow tracker

.github/workflows/manual-test.yml, .github/workflows/recurrent-tests.yml, .github/workflows/run-tests.yml, src/s3_specs/docs/conftest.py
Poder trocar a região e o endpoint url de forma fácil
Adicionei a flag custom --region no pytest onde eu passo a região que quero rodar os testes (br-se1, br-se1-yel, br-ne1, br-ne1-yel) e os valores dos endpoints e region é alterado dinamicamente de acordo com o valor passado em --region.
=> feat: add region flag to change region and endpoint dinamically

.github/workflows/run-tests.yml
Erros sendo mascarados pelo github actions
Devido a alguma alteração realizada no workflow do github, os testes passaram a se mostrar como se tivesse tido sucesso, mesmo estando com erros.
=> Fix GitHub Action to fail when pytest tests fail

.gitignore, justfile, pyproject.toml, run_tests_and_generate_report.py, src/s3_specs/docs/acl_test.py, src/s3_specs/docs/benchmark_test.py, src/s3_specs/docs/big_objects_cli.py, src/s3_specs/docs/big_objects_test.py, src/s3_specs/docs/bucket_basic_test.py, src/s3_specs/docs/bucket_sharing_cli.py, src/s3_specs/docs/bucket_sharing_test.py, src/s3_specs/docs/cold_storage_cli.py, src/s3_specs/docs/cold_storage_test.py, src/s3_specs/docs/conftest.py, src/s3_specs/docs/consistency_test.py, src/s3_specs/docs/list_buckets_test.py, src/s3_specs/docs/list_buckets_test_cli.py, src/s3_specs/docs/locking_cli_test.py, src/s3_specs/docs/locking_test.py, src/s3_specs/docs/multiple_objects_test.py, src/s3_specs/docs/object_basic_test.py, src/s3_specs/docs/object_download_cli.py, src/s3_specs/docs/object_locking_cli.py, src/s3_specs/docs/objects_list_cli.py, src/s3_specs/docs/permission_test_cli.py, src/s3_specs/docs/policies_test.py, src/s3_specs/docs/profiles_policies_test.py, src/s3_specs/docs/service_account_test.py, src/s3_specs/docs/unique_bucket_name_test.py, src/s3_specs/docs/versioning_cli_test.py
Facilitar o processo de run nos testes durante o desenvolvimento ou homologação de novas features
Foi adicionado uma flag --dev-run no pytest indicando que é uma dev run para skipar algumas restrições relacionadas a profile e skipar testes que são incompativeis com ambiente de desenvolvimento. Também foi adicionado uma recipe dev no justfile como um atalho para usar no modo dev.
Além disso, foi adicionado uma tag homologacao que roda todos os testes que utilizamos em homologação, e uma recipe no justfile `homologate` que já aplica a tag e executa os testes de homologação.
=> feat: add tags for dev and homologacao

run_tests_and_generate_report.py
Logs não estavam aparecendo no terminal do github actions
Logs estavam indo para o arquivo .log ao invés de serem printados no terminal, adicionado a flag "-s" e alterado a logica de output dos logs, aproveitando a mudança, foi adicionado paralelismo nos tests para uma melhor perfomance!
=> fix: fix logs on github doesn't appear on homolog tests

.github/workflows/recurrent-tests-1h.yml, .github/workflows/recurrent-tests-6h.yml
Apenas adiciona retries nos testes que falham para tentar desconsiderar inconsistências
Ainda depende da sorte, pois inconsistências ocorrem, principalmente, por load balancer - que vai guiar os resultados para diferentes intâncias do servidor. Esperar não afeta o resultado tanto, mas fazer vários traz mais chance de atingir o servidor correto
=> feat: rerun tests multiple times to prevent inconsistency
